In [ ]:
pip install thefuzz

Collecting thefuzz
  Downloading thefuzz-0.22.1-py3-none-any.whl.metadata (3.9 kB)
Collecting rapidfuzz<4.0.0,>=3.0.0 (from thefuzz)
  Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading thefuzz-0.22.1-py3-none-any.whl (8.2 kB)
Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 32.5 MB/s eta 0:00:00
Installing collected packages: rapidfuzz, thefuzz
Successfully installed rapidfuzz-3.14.5 thefuzz-0.22.1

In [ ]:
import pandas as pd
import re
from thefuzz import process

In [ ]:
df_erp = pd.read_csv("/content/Procurement_data.csv")
df_bank = pd.read_csv("/content/Bank_ledger.csv")
df_risk = pd.read_csv("/content/Vendor_risk.csv")

In [ ]:
df_erp

    PO_Number       Vendor_Name    Order_Date  Order_Value       Category
0     PO-1001    Fast-Track Inc    23/01/2025     32535.07       Services
1     PO-1002  Glob@l Logistics  Feb 04, 2025      5974.04       Hardware
2     PO-1003    Apex Solutions    2025-09-06     11684.60       Hardware
3     PO-1004  Global Logistics    2025-10-16      6083.96  Raw Materials
4     PO-1005   Zenith Supplies    01/12/2025     22524.31      Logistics
..        ...               ...           ...          ...            ...
205   PO-1116         Alpha Mfg    2025-01-21     21602.71  Raw Materials
206   PO-1070  Titan Industrial    12/01/2025     41761.99  Raw Materials
207   PO-1171  Titan Industrial    24/11/2025     16019.12  Raw Materials
208   PO-1175    Apex Solutions    10/08/2025     10825.90  Raw Materials
209   PO-1046   Zenith Supplies    2026-01-09      9232.76       Hardware

[210 rows x 5 columns]

In [ ]:
df_bank

,Transaction_ID,Remittance_Details,Amount_Paid,Payment_Date
0,TXN7001,PAYMENT_CONFIRM_REF_20932_FOR_PO-1001_ID,29281.56,2025-10-29
1,TXN7002,PAYMENT_CONFIRM_REF_82629_FOR_PO-1002_ID,2987.02,2025-10-29
2,TXN7003,PAYMENT_CONFIRM_REF_80312_FOR_PO-1003_ID,11684.60,2025-10-29
3,TXN7004,PAYMENT_CONFIRM_REF_21929_FOR_PO-1004_ID,6083.96,2025-10-29
4,TXN7005,PAYMENT_CONFIRM_REF_77862_FOR_PO-1005_ID,23650.53,2025-10-29
...,...,...,...,...
164,TXN7165,PAYMENT_CONFIRM_REF_49613_FOR_PO-1165_ID,8644.51,2025-10-29
165,TXN7166,PAYMENT_CONFIRM_REF_49010_FOR_PO-1166_ID,23025.56,2025-10-29
166,TXN7167,PAYMENT_CONFIRM_REF_63111_FOR_PO-1167_ID,15207.18,2025-10-29
167,TXN7168,PAYMENT_CONFIRM_REF_40185_FOR_PO-1168_ID,20576.93,2025-10-29
168,TXN7169,PAYMENT_CONFIRM_REF_59188_FOR_PO-1169_ID,8306.43,2025-10-29

In [ ]:
df_risk

,Legal_Entity_Name,HQ_Country,Credit_Score,Financial_Health_Rating
0,Global Logistics Global Group,USA,641,D
1,Fast-Track Inc Global Group,UK,630,B
2,BlueSky Corp Global Group,Germany,579,D
3,Apex Solutions Global Group,India,814,F
4,Alpha Mfg Global Group,China,577,B
5,Zenith Supplies Global Group,Japan,361,D
6,Titan Industrial Global Group,Brazil,592,A

In [ ]:
df_erp.shape

(210, 5)

In [ ]:
df_bank.shape

(169, 4)

In [ ]:
df_risk.shape

(7, 4)

In [ ]:
df_erp.isnull().sum()

PO_Number      0
Vendor_Name    0
Order_Date     0
Order_Value    0
Category       0
dtype: int64

In [ ]:
df_bank.isnull().sum()

Transaction_ID        0
Remittance_Details    0
Amount_Paid           0
Payment_Date          0
dtype: int64

In [ ]:
df_risk.isnull().sum()

Legal_Entity_Name          0
HQ_Country                 0
Credit_Score               0
Financial_Health_Rating    0
dtype: int64

In [ ]:
df_erp.duplicated().sum()

np.int64(10)

In [ ]:
df_bank.duplicated().sum()

np.int64(0)

In [ ]:
df_risk.duplicated().sum()

np.int64(0)

In [ ]:
df_erp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PO_Number    210 non-null    object
 1   Vendor_Name  210 non-null    object
 2   Order_Date   210 non-null    object
 3   Order_Value  210 non-null    float64
 4   Category     210 non-null    object
dtypes: float64(1), object(4)
memory usage: 8.3+ KB

In [ ]:
df_bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      169 non-null    object
 1   Remittance_Details  169 non-null    object
 2   Amount_Paid         169 non-null    float64
 3   Payment_Date        169 non-null    object
dtypes: float64(1), object(3)
memory usage: 5.4+ KB

In [ ]:
df_risk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Legal_Entity_Name        7 non-null      object
 1   HQ_Country               7 non-null      object
 2   Credit_Score             7 non-null      int64
 3   Financial_Health_Rating  7 non-null      object
dtypes: int64(1), object(3)
memory usage: 356.0+ bytes

In [ ]:
df_erp.describe(include="all")

       PO_Number       Vendor_Name  Order_Date   Order_Value  Category
count        210               210         210    210.000000       210
unique       200                11         184           NaN         4
top      PO-1046  Titan Industrial  13/01/2025           NaN  Services
freq           2                33           3           NaN        59
mean         NaN               NaN         NaN  24687.196857       NaN
std          NaN               NaN         NaN  14100.230265       NaN
min          NaN               NaN         NaN    687.950000       NaN
25%          NaN               NaN         NaN  11728.942500       NaN
50%          NaN               NaN         NaN  24461.715000       NaN
75%          NaN               NaN         NaN  36737.192500       NaN
max          NaN               NaN         NaN  49077.910000       NaN

In [ ]:
df_bank.describe(include = "all")

,Transaction_ID,Remittance_Details,Amount_Paid,Payment_Date
count,169,169,169.000000,169
unique,169,169,NaN,1
top,TXN7001,PAYMENT_CONFIRM_REF_20932_FOR_PO-1001_ID,NaN,2025-10-29
freq,1,1,NaN,169
mean,NaN,NaN,21266.068994,NaN
std,NaN,NaN,12948.974410,NaN
min,NaN,NaN,344.380000,NaN
25%,NaN,NaN,10074.520000,NaN
50%,NaN,NaN,21952.310000,NaN
75%,NaN,NaN,31563.850000,NaN
max,NaN,NaN,50515.440000,NaN

In [ ]:
df_risk.describe(include="all")

,Legal_Entity_Name,HQ_Country,Credit_Score,Financial_Health_Rating
count,7,7,7.000000,7
unique,7,7,NaN,4
top,Global Logistics Global Group,USA,NaN,D
freq,1,1,NaN,3
mean,NaN,NaN,599.142857,NaN
std,NaN,NaN,133.245924,NaN
min,NaN,NaN,361.000000,NaN
25%,NaN,NaN,578.000000,NaN
50%,NaN,NaN,592.000000,NaN
75%,NaN,NaN,635.500000,NaN
max,NaN,NaN,814.000000,NaN

In [ ]:
df_erp.head(5)

  PO_Number       Vendor_Name    Order_Date  Order_Value       Category
0   PO-1001    Fast-Track Inc    23/01/2025     32535.07       Services
1   PO-1002  Glob@l Logistics  Feb 04, 2025      5974.04       Hardware
2   PO-1003    Apex Solutions    2025-09-06     11684.60       Hardware
3   PO-1004  Global Logistics    2025-10-16      6083.96  Raw Materials
4   PO-1005   Zenith Supplies    01/12/2025     22524.31      Logistics

In [ ]:
df_erp.rename(columns={"Order_Value":"Committed_Spend"},inplace = True)

In [ ]:

df_erp

    PO_Number       Vendor_Name    Order_Date  Committed_Spend       Category
0     PO-1001    Fast-Track Inc    23/01/2025         32535.07       Services
1     PO-1002  Glob@l Logistics  Feb 04, 2025          5974.04       Hardware
2     PO-1003    Apex Solutions    2025-09-06         11684.60       Hardware
3     PO-1004  Global Logistics    2025-10-16          6083.96  Raw Materials
4     PO-1005   Zenith Supplies    01/12/2025         22524.31      Logistics
..        ...               ...           ...              ...            ...
205   PO-1116         Alpha Mfg    2025-01-21         21602.71  Raw Materials
206   PO-1070  Titan Industrial    12/01/2025         41761.99  Raw Materials
207   PO-1171  Titan Industrial    24/11/2025         16019.12  Raw Materials
208   PO-1175    Apex Solutions    10/08/2025         10825.90  Raw Materials
209   PO-1046   Zenith Supplies    2026-01-09          9232.76       Hardware

[210 rows x 5 columns]

In [ ]:
df_bank.head(5)

,Transaction_ID,Remittance_Details,Amount_Paid,Payment_Date
0,TXN7001,PAYMENT_CONFIRM_REF_20932_FOR_PO-1001_ID,29281.56,2025-10-29
1,TXN7002,PAYMENT_CONFIRM_REF_82629_FOR_PO-1002_ID,2987.02,2025-10-29
2,TXN7003,PAYMENT_CONFIRM_REF_80312_FOR_PO-1003_ID,11684.60,2025-10-29
3,TXN7004,PAYMENT_CONFIRM_REF_21929_FOR_PO-1004_ID,6083.96,2025-10-29
4,TXN7005,PAYMENT_CONFIRM_REF_77862_FOR_PO-1005_ID,23650.53,2025-10-29

In [ ]:
df_bank.rename(columns={"Remittance_Details":"Transaction_Narrative"},inplace=True)

In [ ]:
df_bank.head(5)

,Transaction_ID,Transaction_Narrative,Amount_Paid,Payment_Date
0,TXN7001,PAYMENT_CONFIRM_REF_20932_FOR_PO-1001_ID,29281.56,2025-10-29
1,TXN7002,PAYMENT_CONFIRM_REF_82629_FOR_PO-1002_ID,2987.02,2025-10-29
2,TXN7003,PAYMENT_CONFIRM_REF_80312_FOR_PO-1003_ID,11684.60,2025-10-29
3,TXN7004,PAYMENT_CONFIRM_REF_21929_FOR_PO-1004_ID,6083.96,2025-10-29
4,TXN7005,PAYMENT_CONFIRM_REF_77862_FOR_PO-1005_ID,23650.53,2025-10-29

In [ ]:
df_risk.head(5)

,Legal_Entity_Name,HQ_Country,Credit_Score,Financial_Health_Rating
0,Global Logistics Global Group,USA,641,D
1,Fast-Track Inc Global Group,UK,630,B
2,BlueSky Corp Global Group,Germany,579,D
3,Apex Solutions Global Group,India,814,F
4,Alpha Mfg Global Group,China,577,B

In [ ]:
df_risk.rename(columns={"Legal_Entity_Name":"Entity_Name","HQ_Country":"Country","Financial_Health_Rating":"Financial_Rating"},inplace = True)

In [ ]:
df_risk

                     Entity_Name  Country  Credit_Score Financial_Rating
0  Global Logistics Global Group      USA           641                D
1    Fast-Track Inc Global Group       UK           630                B
2      BlueSky Corp Global Group  Germany           579                D
3    Apex Solutions Global Group    India           814                F
4         Alpha Mfg Global Group    China           577                B
5   Zenith Supplies Global Group    Japan           361                D
6  Titan Industrial Global Group   Brazil           592                A

In [ ]:
df_erp["Order_Date"]

0        23/01/2025
1      Feb 04, 2025
2        2025-09-06
3        2025-10-16
4        01/12/2025
           ...
205      2025-01-21
206      12/01/2025
207      24/11/2025
208      10/08/2025
209      2026-01-09
Name: Order_Date, Length: 210, dtype: object

In [ ]:
df_erp["Vendor_Name"].unique()

array(['Fast-Track Inc', 'Glob@l Logistics', 'Apex Solutions',
       'Global Logistics', 'Zenith Supplies', 'Titan Industrial',
       'Tit@n Industri@l', 'BlueSky Corp', 'Alpha Mfg', 'F@st-Tr@ck Ltd',
       'BlueSky Ltd'], dtype=object)

In [ ]:
def flexible_date_cleaner(date_str):
    if pd.isna(date_str) or str(date_str).strip() == "":
        return pd.NaT

    # Try 1: Explicitly try Day-First (e.g., 25/12/2025)
    # This silences the warning because we are telling Pandas what to expect.
    try:
        return pd.to_datetime(date_str, dayfirst=True, errors='raise')
    except:
        # Try 2: Try Year-First or Month-First (e.g., 2025-12-25)
        try:
            return pd.to_datetime(date_str, dayfirst=False, errors='raise')
        except:
            # Try 3: Mixed/Text format (e.g., "Jan 5, 2025")
            try:
                return pd.to_datetime(date_str, format='mixed', errors='raise')
            except:
                return pd.NaT

# Apply the fixed function
df_erp['Order_Date'] = df_erp['Order_Date'].apply(flexible_date_cleaner)

/tmp/ipykernel_17060/2900646750.py:8: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  return pd.to_datetime(date_str, dayfirst=True, errors='raise')

In [ ]:
df_erp['Order_Date']

0     2025-01-23
1     2025-02-04
2     2025-06-09
3     2025-10-16
4     2025-12-01
         ...
205   2025-01-21
206   2025-01-12
207   2025-11-24
208   2025-08-10
209   2026-09-01
Name: Order_Date, Length: 210, dtype: datetime64[ns]

In [ ]:
df_erp

    PO_Number       Vendor_Name Order_Date  Committed_Spend       Category
0     PO-1001    Fast-Track Inc 2025-01-23         32535.07       Services
1     PO-1002  Glob@l Logistics 2025-02-04          5974.04       Hardware
2     PO-1003    Apex Solutions 2025-06-09         11684.60       Hardware
3     PO-1004  Global Logistics 2025-10-16          6083.96  Raw Materials
4     PO-1005   Zenith Supplies 2025-12-01         22524.31      Logistics
..        ...               ...        ...              ...            ...
205   PO-1116         Alpha Mfg 2025-01-21         21602.71  Raw Materials
206   PO-1070  Titan Industrial 2025-01-12         41761.99  Raw Materials
207   PO-1171  Titan Industrial 2025-11-24         16019.12  Raw Materials
208   PO-1175    Apex Solutions 2025-08-10         10825.90  Raw Materials
209   PO-1046   Zenith Supplies 2026-09-01          9232.76       Hardware

[210 rows x 5 columns]

In [ ]:
df_risk

                     Entity_Name  Country  Credit_Score Financial_Rating
0  Global Logistics Global Group      USA           641                D
1    Fast-Track Inc Global Group       UK           630                B
2      BlueSky Corp Global Group  Germany           579                D
3    Apex Solutions Global Group    India           814                F
4         Alpha Mfg Global Group    China           577                B
5   Zenith Supplies Global Group    Japan           361                D
6  Titan Industrial Global Group   Brazil           592                A

In [ ]:
risk_name = df_risk["Entity_Name"].to_list()

In [ ]:
def match_vendor(name):
  match,score = process.extractOne(str(name),risk_name)
  return match if score > 70 else "Unknown"

In [ ]:
df_erp["Vendor_Name"] = df_erp["Vendor_Name"].apply(match_vendor)

In [ ]:
df_erp

,PO_Number,Vendor_Name,Order_Date,Committed_Spend,Category
0,PO-1001,Fast-Track Inc Global Group,2025-01-23,32535.07,Services
1,PO-1002,Global Logistics Global Group,2025-02-04,5974.04,Hardware
2,PO-1003,Apex Solutions Global Group,2025-06-09,11684.60,Hardware
3,PO-1004,Global Logistics Global Group,2025-10-16,6083.96,Raw Materials
4,PO-1005,Zenith Supplies Global Group,2025-12-01,22524.31,Logistics
...,...,...,...,...,...
205,PO-1116,Alpha Mfg Global Group,2025-01-21,21602.71,Raw Materials
206,PO-1070,Titan Industrial Global Group,2025-01-12,41761.99,Raw Materials
207,PO-1171,Titan Industrial Global Group,2025-11-24,16019.12,Raw Materials
208,PO-1175,Apex Solutions Global Group,2025-08-10,10825.90,Raw Materials
209,PO-1046,Zenith Supplies Global Group,2026-09-01,9232.76,Hardware

In [ ]:
df_bank

,Transaction_ID,Transaction_Narrative,Amount_Paid,Payment_Date
0,TXN7001,PAYMENT_CONFIRM_REF_20932_FOR_PO-1001_ID,29281.56,2025-10-29
1,TXN7002,PAYMENT_CONFIRM_REF_82629_FOR_PO-1002_ID,2987.02,2025-10-29
2,TXN7003,PAYMENT_CONFIRM_REF_80312_FOR_PO-1003_ID,11684.60,2025-10-29
3,TXN7004,PAYMENT_CONFIRM_REF_21929_FOR_PO-1004_ID,6083.96,2025-10-29
4,TXN7005,PAYMENT_CONFIRM_REF_77862_FOR_PO-1005_ID,23650.53,2025-10-29
...,...,...,...,...
164,TXN7165,PAYMENT_CONFIRM_REF_49613_FOR_PO-1165_ID,8644.51,2025-10-29
165,TXN7166,PAYMENT_CONFIRM_REF_49010_FOR_PO-1166_ID,23025.56,2025-10-29
166,TXN7167,PAYMENT_CONFIRM_REF_63111_FOR_PO-1167_ID,15207.18,2025-10-29
167,TXN7168,PAYMENT_CONFIRM_REF_40185_FOR_PO-1168_ID,20576.93,2025-10-29
168,TXN7169,PAYMENT_CONFIRM_REF_59188_FOR_PO-1169_ID,8306.43,2025-10-29

In [ ]:
df_bank['PO_Key'] = df_bank['Transaction_Narrative'].str.extract(r'(PO-\d+)')

In [ ]:
df_bank

,Transaction_ID,Transaction_Narrative,Amount_Paid,Payment_Date,PO_Key
0,TXN7001,PAYMENT_CONFIRM_REF_20932_FOR_PO-1001_ID,29281.56,2025-10-29,PO-1001
1,TXN7002,PAYMENT_CONFIRM_REF_82629_FOR_PO-1002_ID,2987.02,2025-10-29,PO-1002
2,TXN7003,PAYMENT_CONFIRM_REF_80312_FOR_PO-1003_ID,11684.60,2025-10-29,PO-1003
3,TXN7004,PAYMENT_CONFIRM_REF_21929_FOR_PO-1004_ID,6083.96,2025-10-29,PO-1004
4,TXN7005,PAYMENT_CONFIRM_REF_77862_FOR_PO-1005_ID,23650.53,2025-10-29,PO-1005
...,...,...,...,...,...
164,TXN7165,PAYMENT_CONFIRM_REF_49613_FOR_PO-1165_ID,8644.51,2025-10-29,PO-1165
165,TXN7166,PAYMENT_CONFIRM_REF_49010_FOR_PO-1166_ID,23025.56,2025-10-29,PO-1166
166,TXN7167,PAYMENT_CONFIRM_REF_63111_FOR_PO-1167_ID,15207.18,2025-10-29,PO-1167
167,TXN7168,PAYMENT_CONFIRM_REF_40185_FOR_PO-1168_ID,20576.93,2025-10-29,PO-1168
168,TXN7169,PAYMENT_CONFIRM_REF_59188_FOR_PO-1169_ID,8306.43,2025-10-29,PO-1169

In [ ]:
df_bank.head(5)

,Transaction_ID,Transaction_Narrative,Amount_Paid,Payment_Date,PO_Key
0,TXN7001,PAYMENT_CONFIRM_REF_20932_FOR_PO-1001_ID,29281.56,2025-10-29,PO-1001
1,TXN7002,PAYMENT_CONFIRM_REF_82629_FOR_PO-1002_ID,2987.02,2025-10-29,PO-1002
2,TXN7003,PAYMENT_CONFIRM_REF_80312_FOR_PO-1003_ID,11684.60,2025-10-29,PO-1003
3,TXN7004,PAYMENT_CONFIRM_REF_21929_FOR_PO-1004_ID,6083.96,2025-10-29,PO-1004
4,TXN7005,PAYMENT_CONFIRM_REF_77862_FOR_PO-1005_ID,23650.53,2025-10-29,PO-1005

In [ ]:
df_erp.head(5)

,PO_Number,Vendor_Name,Order_Date,Committed_Spend,Category
0,PO-1001,Fast-Track Inc Global Group,2025-01-23,32535.07,Services
1,PO-1002,Global Logistics Global Group,2025-02-04,5974.04,Hardware
2,PO-1003,Apex Solutions Global Group,2025-06-09,11684.60,Hardware
3,PO-1004,Global Logistics Global Group,2025-10-16,6083.96,Raw Materials
4,PO-1005,Zenith Supplies Global Group,2025-12-01,22524.31,Logistics

In [ ]:
df_risk.head(5)

                     Entity_Name  Country  Credit_Score Financial_Rating
0  Global Logistics Global Group      USA           641                D
1    Fast-Track Inc Global Group       UK           630                B
2      BlueSky Corp Global Group  Germany           579                D
3    Apex Solutions Global Group    India           814                F
4         Alpha Mfg Global Group    China           577                B

In [ ]:
df_erp.to_csv("Procurement_data.csv",index=False)
df_risk.to_csv("Vendor_risk.csv",index = False)
df_bank.to_csv("Bank_ledger.csv",index=False)